# Generated by Django 3.2.7 on 2021-10-01 13:52

import api.all_models.product_image
import api.all_models.shop
import api.all_models.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Имя на кыргызском')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('title_slug', models.SlugField(max_length=200, verbose_name='Ссылка для seo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Имя на кыргызском')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('title_slug', models.SlugField(max_length=200, verbose_name='Ссылка для seo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kg', models.IntegerField(db_index=True, verbose_name='Цена kg')),
                ('price_ru', models.IntegerField(db_index=True, verbose_name='Цена ru')),
                ('previous_price_kg', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('previous_price_ru', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('sold_count', models.IntegerField(default=0, verbose_name='Цифра продажи')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalog', verbose_name='Каталог')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Best')])),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.ImageField(upload_to=api.all_models.shop.rename)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.all_models.user.rename, verbose_name='Изображение')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.role', verbose_name='Роль')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.TextField(verbose_name='Токен')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Имя на кыргызском')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('title_slug', models.SlugField(max_length=200, verbose_name='Ссылка для seo')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rating', verbose_name='Рейтинг')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.all_models.product_image.rename)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcatalog', verbose_name='Под каталог'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.subcatalog'),
        ),
    ]
