# Generated by Django 3.2.7 on 2021-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211002_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='isShowOwner',
            field=models.BooleanField(default=False, verbose_name='Имеет магазин?'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
