# Generated by Django 3.2.7 on 2021-10-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211004_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isShowOwner',
            new_name='isShopOwner',
        ),
    ]
