# Generated by Django 3.2.7 on 2021-10-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_isshowowner_user_isshopowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.user', verbose_name='Пользователь'),
        ),
    ]
