# Generated by Django 3.2.7 on 2021-10-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211004_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartId',
            field=models.UUIDField(blank=True, null=True, verbose_name='Id корзины'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.cart'),
        ),
    ]
