# Generated by Django 3.2.7 on 2021-10-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211004_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
    ]
